### ISSUE TITLE
Sort algorithm

### ISSUE THREAD

**Issue by pepa65** [veer66/chamkho#6]
What is the sort algorithm on the dictionary? Or does it not matter??
I need to add some more words to the Thai list.

**Comment by veer66** [comment]
ใช้ LANG=c sort ของ GNU ครับ

**Comment by veer66** [comment]
> It seems like it doesn't matter where you put any new word in the list, the app will pick it up.

Unsorted list doesn't always work. So please sort it.

**Comment by pepa65** [comment]
I sorted the existing lists with `LANG=C sort` (GNU coreutils 8.32), but the result was always different from the original list.

**Comment by veer66** [comment]
ผม sort thai.txt ใหม่แล้วครับ

**Comment by pepa65** [comment]
ภาษาอื่นๆ มีปัญหาเดียวกันครับ

**Comment by pepa65** [comment]
`LANG=C sort` และ `LANG=C LC_ALL=C sort` ไม่เหมือนกัน
